### ISSUE TITLE
cl-delete

### ISSUE THREAD

**Issue by nicolas-graves** [nicolas-graves/org-dynamic-agenda#2]
@hpfr Regarding commit f2f2358444491375091a99d4f6db61a85c039fd9, isn't cl-delete supposed to be the same as cl-remove but acting in place ? 

```
(let ((l '("3" "4" "1" "5" "6"))) (cl-delete "1" l :test #'string-equal) l)
```
The above code seems to do exactly what I want from it.

**Comment by hpfr** [comment]
Thanks for merging #1!

From the docstring of `cl-delete`:

> This is a destructive function; it reuses the storage of SEQ whenever possible.

The important part here is “whenever possible”; this is not always the case. Your example happens to work, returning `("3" "4" "5" "6")` but if we try another, prepending another `"1"`:

```elisp
(let ((l '("1" "3" "4" "1" "5" "6"))) (cl-delete "1" l :test #'string-equal) l)
```

You will see this example returns `("1" "3" "4" "5" "6")`. Now if we drop the final `l`:

```elisp
(let ((l '("1" "3" "4" "1" "5" "6"))) (cl-delete "1" l :test #'string-equal))
```

This returns `("3" "4" "5" "6")` again. So `cl-delete` does damage the original list, unlike `cl-remove`, but this does not necessarily leave the desired result at the original memory location. As I understand it, `cl-delete` just has minor performance benefits (memory usage) over `cl-remove`, but the API is the same (i.e. different from `cl-pushnew`).

**Comment by nicolas-graves** [comment]
Thanks, I understand now. I force pushed the repo without the commit removal, so it's back there.
